/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Formularios;

import Entidades.Render;
import Conexion.conector;
import Models.AsientoModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gergo
 */
public class registrot extends javax.swing.JPanel {

    /**
     * Creates new form registrot
     */
    String vFecha,vDescriP,vNP,vSaldoi,vCargo,vAbono;
    DefaultTableModel jtModelo,JTableModel2;
    AsientoModel cn;
    int contador=0;

    public registrot() throws SQLException{
        initComponents();
            cn = new AsientoModel();

        this.cargoabono();
       jtModelo = (DefaultTableModel) this.tablaLB.getModel();
       JTableModel2 = (DefaultTableModel) this.tablaEC.getModel();
       this.cargarDatos();
       this.saldoInic();


        
    }
     public void cargarDatos() throws SQLException {

        jtModelo = cn.obtenerDatos();
        this.tablaLB.setModel(jtModelo);
        this.tablaLB.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);

    }
    public void cargoabono(){
        if(cargoB.isSelected()==true){
                cargoJ.setEnabled(true);
                cargoJ.setText("");
                abonoJ.setText("0");
                abonoJ.setEnabled(false);
        }
        if(abonoB.isSelected()==true){
                abonoJ.setEnabled(true);
                abonoJ.setText("");
                cargoJ.setText("0");
                cargoJ.setEnabled(false);
        }
        
    }
    public void limpiarjtex() {

        this.Descrip.setText("");
        fechFC.setCalendar(null);

    }
    public void saldoInic(){
        if (tablaLB.getRowCount() == 0){
            this.panelEC.setVisible(false);
            this.panelLB.setVisible(false);
            this.panel1.setVisible(false);
            this.LBA.setVisible(false);
            this.ECB.setVisible(false);
            
        }else{
            this.Saldoi.setEnabled(false);
            this.Saldoi.setVisible(false);
            this.IniciarB.setVisible(false);
            this.labelSI.setVisible(false);

            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaLB = new javax.swing.JTable();
        panel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fechFC = new com.toedter.calendar.JDateChooser();
        cargoJ = new javax.swing.JTextField();
        abonoJ = new javax.swing.JTextField();
        cargoB = new javax.swing.JRadioButton();
        abonoB = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        np = new javax.swing.JTextField();
        Descrip = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaEC = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        panelLB = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        saldosLb = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cargoslb = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        abonoslb = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TotalLB = new javax.swing.JTextField();
        panelEC = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        saldoIniciarEC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cargosEC = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        abonosEC = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        totalEC = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        IniciarB = new javax.swing.JButton();
        Saldoi = new javax.swing.JTextField();
        labelSI = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        LBA = new javax.swing.JButton();
        ECB = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setPreferredSize(getPreferredSize());

        tablaLB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero op", "Fecha ", "Descripcion", "Cargo", "Abono", "Saldo", "Eliminar"
            }
        ));
        jScrollPane2.setViewportView(tablaLB);

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Fecha de operaición:");

        abonoJ.setEnabled(false);

        buttonGroup1.add(cargoB);
        cargoB.setText("Cargo");
        cargoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargoBActionPerformed(evt);
            }
        });

        buttonGroup1.add(abonoB);
        abonoB.setText("Abono");
        abonoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abonoBActionPerformed(evt);
            }
        });

        jLabel12.setText("Numero de operacion");

        jLabel3.setText("Decripción");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(53, 53, 53)
                                .addComponent(abonoB))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fechFC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(47, 47, 47)
                                .addComponent(cargoB)))
                        .addGap(26, 26, 26)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cargoJ, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(abonoJ, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(np, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(Descrip, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cargoB)
                            .addComponent(cargoJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(np, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(abonoB)
                            .addComponent(abonoJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Descrip)
                .addGap(18, 18, 18))
        );

        fechFC.getAccessibleContext().setAccessibleName("");

        tablaEC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.op", "Fecha op.", "Desc", "Cargo", "Abono", "Saldo", "Eliminar"
            }
        ));
        jScrollPane3.setViewportView(tablaEC);

        jButton3.setText("Guardar cambios");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Procesar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        panelLB.setBackground(new java.awt.Color(255, 255, 255));
        panelLB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Saldo Inicial:");

        saldosLb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldosLbActionPerformed(evt);
            }
        });

        jLabel5.setText("Total Cargos:");

        jLabel6.setText("Total Abonos:");

        jLabel7.setText("Saldo segun libro de bancos");

        javax.swing.GroupLayout panelLBLayout = new javax.swing.GroupLayout(panelLB);
        panelLB.setLayout(panelLBLayout);
        panelLBLayout.setHorizontalGroup(
            panelLBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLBLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(saldosLb, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cargoslb, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(abonoslb, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLBLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(TotalLB, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        panelLBLayout.setVerticalGroup(
            panelLBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(saldosLb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cargoslb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(abonoslb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TotalLB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        panelEC.setBackground(new java.awt.Color(255, 255, 255));
        panelEC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setText("Saldo Inicial:");

        jLabel9.setText("Total Cargos:");

        jLabel10.setText("Total Abonos:");

        abonosEC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abonosECActionPerformed(evt);
            }
        });

        jLabel11.setText("Saldo segun libro de bancos");

        javax.swing.GroupLayout panelECLayout = new javax.swing.GroupLayout(panelEC);
        panelEC.setLayout(panelECLayout);
        panelECLayout.setHorizontalGroup(
            panelECLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelECLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelECLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelECLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(saldoIniciarEC, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cargosEC, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(abonosEC, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelECLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(totalEC, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        panelECLayout.setVerticalGroup(
            panelECLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelECLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelECLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(saldoIniciarEC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cargosEC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(abonosEC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelECLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(totalEC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setName(""); // NOI18N

        IniciarB.setText("Iniciar");
        IniciarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarBActionPerformed(evt);
            }
        });

        labelSI.setText("Saldo Inicial:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(IniciarB, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(Saldoi, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(labelSI)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSI)
                .addGap(18, 18, 18)
                .addComponent(Saldoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(IniciarB)
                .addGap(19, 19, 19))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LBA.setText("Agregar Libro Banco");
        LBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LBAActionPerformed(evt);
            }
        });

        ECB.setText("Agragar a estado de cuenta");
        ECB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ECBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(LBA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 463, Short.MAX_VALUE)
                .addComponent(ECB)
                .addGap(259, 259, 259))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBA)
                    .addComponent(ECB)))
        );

        jButton1.setText("Limpiar");

        jButton2.setText("Exportar CSV");

        jButton5.setText("Generar informe");

        jButton6.setText("No se boton");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2)
                                    .addComponent(panelLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(panelEC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3))))
                        .addGap(56, 56, 56))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton1)
                            .addComponent(jButton5))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton2)
                            .addComponent(jButton6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelEC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleParent(this);
    }// </editor-fold>//GEN-END:initComponents

    private void LBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LBAActionPerformed
        // TODO add your handling code here:
        //CREACION DE VARIABLES PARA TEXTO
        vDescriP = this.Descrip.getText();
        vCargo = this.cargoJ.getText();
        vAbono = this.abonoJ.getText();
        vNP = this.np.getText();
        vSaldoi = this.Saldoi.getText();
        
        //VALIDACIONES DEL INGRESO DE DATOS A LAS TABLAS
        if(fechFC.getDate()==null ||(Descrip.getText().trim().length() == 0) 
                || (vCargo.trim().length()==0) || (vAbono.trim().length()==0)|| (vNP.trim().length()==0)
                || (vSaldoi.trim().length()==0)){
            //MENSAJE SI ESTAN NULOS
             JOptionPane.showMessageDialog(null, "Por favor Complete los datos.", "Advertencia", JOptionPane.WARNING_MESSAGE);

    
        }
        else{
            //renderizamos boton eleminar
             tablaLB.setDefaultRenderer(Object.class, new Render());

            
            
                SimpleDateFormat DateFor = new SimpleDateFormat("yyyy-MM-dd");
                vFecha = DateFor.format(fechFC.getDate());

            //Iniciamos variables para convertir datos a float o double
            double vvCargo, vvAbono;
            vvCargo = Double.valueOf(vCargo);
            vvAbono = Double.valueOf(vAbono);
            //System.out.println("" + vvdebe + "" + vvhaber);

                //verficacion de numeros negativos
                if (vvCargo < 0 || vvAbono < 0) {
                    
                    JOptionPane.showMessageDialog(null, "Los valores no deben ser negativos", "Advertencia", JOptionPane.WARNING_MESSAGE);
                } else {
                    JButton btn2 = new JButton("Eliminar");
                    btn2.setName("e");

                    jtModelo.addRow(new Object[]{
                        vNP, vFecha,vDescriP, vCargo,vAbono, btn2
                    });
                    this.limpiarjtex();

                }
               
        }
       
        
    }//GEN-LAST:event_LBAActionPerformed

    private void cargoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargoBActionPerformed
        // TODO add your handling code here:
        this.cargoabono();
    }//GEN-LAST:event_cargoBActionPerformed

    private void abonoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abonoBActionPerformed
        // TODO add your handling code here:
                this.cargoabono();

    }//GEN-LAST:event_abonoBActionPerformed

    private void saldosLbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldosLbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saldosLbActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        conector cc = new conector();
        Connection cn = cc.conectar();
        int cont = 0;
        String consult = "insert into librobanco(op,saldoinicial,cargo,abono,descrip,fecha) values(?,?,?,?,?,?)";
        double sumA = 0, sumC = 0,saldoInicial=0;

        //sacamos totales de abonos y cargos TABLA LB
        for (int i = 0; i < tablaLB.getRowCount(); i++) {
            System.out.println("entre al priemer for");
            if(i==1){
                saldoInicial= Double.valueOf((String) tablaLB.getValueAt(i, 5));

            }
            sumA = sumA + Double.valueOf((String) tablaLB.getValueAt(i, 4));
            sumC = sumC + Double.valueOf((String) tablaLB.getValueAt(i, 3));

        }
        //DATOS FINALES TABLA LB
        this.abonoslb.setText(""+sumA);
        this.cargoslb.setText(""+sumC);
        this.saldosLb.setText(""+saldoInicial);
        Double VTotalLB=saldoInicial+sumA-sumC;
        this.TotalLB.setText(""+VTotalLB);
        
        sumA = 0;
        sumC = 0;
        saldoInicial=0;
        //sacamos totales de abonos y cargos de TABLA EC
        for (int i = 0; i < tablaEC.getRowCount(); i++) {
            System.out.println("entre al priemer for");
            if(i==1){
                saldoInicial= Double.valueOf((String) tablaEC.getValueAt(i, 5));

            }
            sumA = sumA + Double.valueOf((String) tablaEC.getValueAt(i, 4));
            sumC = sumC + Double.valueOf((String) tablaEC.getValueAt(i, 3));

        }
        this.abonosEC.setText(""+sumA);
        this.cargosEC.setText(""+sumC);
        this.saldoIniciarEC.setText(""+saldoInicial);
        Double VTotalEC=saldoInicial+sumA-sumC;
        this.TotalLB.setText(""+VTotalEC);
        
        //insertamos en la base
             try {
                //Statement stmt = cn.createStatement();

                if (tablaLB.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(null, "No Existen Datos", "Advertencia", JOptionPane.WARNING_MESSAGE);
                } else {
                    System.out.println("aqui siiiiiiu");
                    for (int i = 0; i < tablaLB.getRowCount(); i++) {
                        vNP = (String) tablaLB.getValueAt(i, 0);
                        vFecha = (String) tablaLB.getValueAt(i, 1);
                        vDescriP = (String) tablaLB.getValueAt(i, 2);
                        vCargo = (String) tablaLB.getValueAt(i, 3);
                        vAbono = (String) tablaLB.getValueAt(i, 4);

                        PreparedStatement ps = cn.prepareStatement(consult);
                        
  
     
                            ps.setInt(1, Integer.parseInt(vNP));
                            ps.setDouble(2, Double.parseDouble(vSaldoi));
                            ps.setDouble(3, Double.parseDouble(vCargo));
                            ps.setDouble(4, Double.parseDouble(vAbono));
                            ps.setString(5, vDescriP);
                            ps.setString(6, vFecha);

                       



                 
                        ps.executeUpdate();

                    }
                    JOptionPane.showMessageDialog(null, "Cambios guardados con exito.", "Con exito", JOptionPane.INFORMATION_MESSAGE);

                }

            } catch (Exception e) {

                System.err.println(e.getClass().getName() + ": " + e.getMessage());
            }
        

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton4ActionPerformed

    private void IniciarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarBActionPerformed
        // TODO add your handling code here:
           
            vSaldoi = this.Saldoi.getText();
            this.panelEC.setVisible(true);
            this.panelLB.setVisible(true);
            this.panel1.setVisible(true);
            this.Saldoi.setEnabled(false);
            this.Saldoi.setVisible(false);
            this.IniciarB.setVisible(false);
             this.LBA.setVisible(true);
            this.ECB.setVisible(true);
            this.labelSI.setVisible(false);
             

                    jtModelo.addRow(new Object[]{
                        "0", "0","Saldo Inicial","0","0",vSaldoi
                    });
                    JTableModel2.addRow(new Object[]{
                        "0", "0","Saldo Inicial","0","0",vSaldoi

                    });
        
    }//GEN-LAST:event_IniciarBActionPerformed

    private void abonosECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abonosECActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abonosECActionPerformed

    private void ECBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ECBActionPerformed
        // TODO add your handling code here:
        vDescriP = this.Descrip.getText();
        vCargo = this.cargoJ.getText();
        vAbono = this.abonoJ.getText();
        vNP = this.np.getText();
        vSaldoi = this.Saldoi.getText();
        
        //VALIDACIONES DEL INGRESO DE DATOS A LAS TABLAS
        if(fechFC.getDate()==null ||(Descrip.getText().trim().length() == 0) 
                || (vCargo.trim().length()==0) || (vAbono.trim().length()==0)|| (vNP.trim().length()==0)
                || (vSaldoi.trim().length()==0)){
            //MENSAJE SI ESTAN NULOS
             JOptionPane.showMessageDialog(null, "Por favor Complete los datos.", "Advertencia", JOptionPane.WARNING_MESSAGE);

    
        }
        else{
            //renderizamos boton eleminar
             tablaEC.setDefaultRenderer(Object.class, new Render());

            
            
                SimpleDateFormat DateFor = new SimpleDateFormat("yyyy-MM-dd");
                vFecha = DateFor.format(fechFC.getDate());

            //Iniciamos variables para convertir datos a float o double
            double vvCargo, vvAbono;
            vvCargo = Double.valueOf(vCargo);
            vvAbono = Double.valueOf(vAbono);
            //System.out.println("" + vvdebe + "" + vvhaber);

                //verficacion de numeros negativos
                if (vvCargo < 0 || vvAbono < 0) {
                    
                    JOptionPane.showMessageDialog(null, "Los valores no deben ser negativos", "Advertencia", JOptionPane.WARNING_MESSAGE);
                } else {
                    JButton btn2 = new JButton("Eliminar");
                    btn2.setName("e");

                    JTableModel2.addRow(new Object[]{
                        vNP, vFecha,vDescriP, vCargo,vAbono,"0", btn2
                    });
                    this.limpiarjtex();

                }
        }    
        
    }//GEN-LAST:event_ECBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Descrip;
    private javax.swing.JButton ECB;
    private javax.swing.JButton IniciarB;
    private javax.swing.JButton LBA;
    private javax.swing.JTextField Saldoi;
    private javax.swing.JTextField TotalLB;
    private javax.swing.JRadioButton abonoB;
    private javax.swing.JTextField abonoJ;
    private javax.swing.JTextField abonosEC;
    private javax.swing.JTextField abonoslb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cargoB;
    private javax.swing.JTextField cargoJ;
    private javax.swing.JTextField cargosEC;
    private javax.swing.JTextField cargoslb;
    private com.toedter.calendar.JDateChooser fechFC;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelSI;
    private javax.swing.JTextField np;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panelEC;
    private javax.swing.JPanel panelLB;
    private javax.swing.JTextField saldoIniciarEC;
    private javax.swing.JTextField saldosLb;
    private javax.swing.JTable tablaEC;
    private javax.swing.JTable tablaLB;
    private javax.swing.JTextField totalEC;
    // End of variables declaration//GEN-END:variables
}
